---
title: "Linear models for raw scores"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#tinytex::install_tinytex()
library(tidyverse)
library(cowplot)
data <- read.csv("AD_DECODE_data.csv")

#ad_pat <- which(data$risk_for_ad == 3)

ad <- data %>% 
  filter(! is.na(Weight)) %>% 
  mutate(sex = case_when(
    sex == "F" ~ "Female",
    sex == "M" ~ "Male"
  )) %>% 
  filter(risk_for_ad != 3)

# data by genotypes
e23 <- ad %>% 
  filter(genotype == "APOE23") 
e33 <- ad %>% 
  filter(genotype == "APOE33")
e34 <- ad %>% 
  filter(genotype == "APOE34")

# combining genotypes 
geno_combined <- ad %>% 
  mutate(Genotype = case_when(
    genotype == "APOE23" | genotype == "APOE33" ~ "APOE3",
    genotype == "APOE34" | genotype == "APOE44" ~ "APOE4"
  )) 

# separating by sex
combo_f <- geno_combined %>% 
  filter(sex == "Female")

combo_m <- geno_combined %>% 
  filter(sex == "Male")
```

```{r ufov-1, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = ufov1,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "UFOV1 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV1 score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") 
  #annotate("point", x = 82, y = data, colour = "blue")
  

plot4 <- ggplot(geno_combined, aes(age, ufov1, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV1 score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(ufov1 ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov1 ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov1 ~ age*Genotype, combo_m)
summary(lm_m)
```



```{r ufov-2, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = ufov2,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "UFOV2 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV2 score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") 

plot4 <- ggplot(geno_combined, aes(age, ufov2, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV2 score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(ufov2 ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov2 ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov2 ~ age*Genotype, combo_m)
summary(lm_m)

```


```{r ufov-3, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = ufov3,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "UFOV3 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV3 score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, ufov3, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV3 score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(ufov3 ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov3 ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov3 ~ age*Genotype, combo_m)
summary(lm_m)
```


```{r animals-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = animals,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Animal naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Animal naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, animals, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Animal naming score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(animals ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(animals ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(animals ~ age*Genotype, combo_m)
summary(lm_m)
```


```{r vegetables-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = vegetables,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Vegetable naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Vegetable naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, vegetables, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Vegetable naming score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(vegetables ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(vegetables ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(vegetables ~ age*Genotype, combo_m)
summary(lm_m)
```

```{r f-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = f,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "F words naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "F words naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, f, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "F words naming score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(f ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(f ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(f ~ age*Genotype, combo_m)
summary(lm_m)
```




```{r l-norepeats, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = l,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "L words naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "L words naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, l, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "L words naming score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5)

lm <- lm(l ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(l ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(l ~ age*Genotype, combo_m)
summary(lm_m)

```



```{r trail-A, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = trailA,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Trail A scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail A score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, trailA, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail A score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(trailA ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailA ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailA ~ age*Genotype, combo_m)
summary(lm_m)
```


```{r trail-B, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = trailB,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Trail B scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail B score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, trailB, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail B score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(trailB ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailB ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailB ~ age*Genotype, combo_m)
summary(lm_m)
```


```{r trail-differ, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = trailDiff,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Difference between trail scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail scores difference") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, trailDiff, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail scores difference") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(trailDiff ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailDiff ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailDiff ~ age*Genotype, combo_m)
summary(lm_m)

```


```{r number-spanforwards, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = fwd_total_correct,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Forward Total Correct score linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Forward Total Correct scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, fwd_total_correct, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Forward Total Correct scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(fwd_total_correct ~ age*Genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(fwd_total_correct ~ age*Genotype, combo_f)
summary(lm_f)

lm_m <- lm(fwd_total_correct ~ age*Genotype, combo_m)
summary(lm_m)
```


```{r number-spanbackwards, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = bckwds_total_correct,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Backward Total Correct score linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Backward Total Correct scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, bckwds_total_correct, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Backward Total Correct scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

btot_lm2 <- lm(bckwds_total_correct ~ age*Genotype*sex, geno_combined)
summary(btot_lm2)

btot_lm_f <- lm(bckwds_total_correct ~ age*Genotype, combo_f)
summary(btot_lm_f)

fmax_lm_m <- lm(bckwds_total_correct ~ age*Genotype, combo_m)
summary(btot_lm_m)

```


```{r number-spanfwdsmax, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = fwd_max_length,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Forward Max Length linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Forward Max Length scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, fwd_max_length, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Forward Max Length scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

fmax_lm2 <- lm(fwd_max_length ~ age*Genotype*sex, geno_combined)
summary(fmax_lm2)

fmax_lm_f <- lm(fwd_max_length ~ age*Genotype, combo_f)
summary(fmax_lm_f)

fmax_lm_m <- lm(fwd_max_length ~ age*Genotype, combo_m)
summary(fmax_lm_m)
```


```{r number-spanbckwdsmax, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = bckwds_max_length,
                                 color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Backward Max Length linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Backward Max Length scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, bckwds_max_length, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Backwards Max Length scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

bmax_lm2 <- lm(bckwds_max_length ~ age*Genotype*sex, geno_combined)
summary(bmax_lm2)

bmax_lm_f <- lm(bckwds_max_length ~ age*Genotype, combo_f)
summary(bmax_lm_f)

bmax_lm_m <- lm(bckwds_max_length ~ age*Genotype, combo_m)
summary(bmax_lm_m)
```

```{r ravlt-forg, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_FORGETTING,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "RAVLT forgetting scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT forgetting scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, RAVLT_FORGETTING, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT forgetting scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

fravlt_lm2 <- lm(RAVLT_FORGETTING ~ age*Genotype*sex, geno_combined)
summary(fravlt_lm2)

fravlt_lm_f <- lm(RAVLT_FORGETTING ~ age*Genotype, combo_f)
summary(fravlt_lm_f)

fravlt_lm_m <- lm(RAVLT_FORGETTING ~ age*Genotype, combo_m)
summary(fravlt_lm_m)
```

```{r ravlt-learn, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_LEARNING,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "RAVLT learning scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT learning scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, RAVLT_LEARNING, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT learning scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lravlt_lm2 <- lm(RAVLT_LEARNING ~ age*Genotype*sex, geno_combined)
summary(lravlt_lm2)

lravlt_lm_f <- lm(RAVLT_LEARNING ~ age*Genotype, combo_f)
summary(lravlt_lm_f)

lravlt_lm_m <- lm(RAVLT_LEARNING ~ age*Genotype, combo_m)
summary(lravlt_lm_m)
```

```{r ravlt-imm, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_IMMEDIATE,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "RAVLT Immediate scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT Immediate scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, RAVLT_IMMEDIATE, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT Immediate scores") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

imravlt_lm2 <- lm(RAVLT_IMMEDIATE ~ age*Genotype*sex, geno_combined)
summary(imravlt_lm2)

imravlt_lm_f <- lm(RAVLT_IMMEDIATE ~ age*Genotype, combo_f)
summary(imravlt_lm_f)

imravlt_lm_m <- lm(RAVLT_IMMEDIATE ~ age*Genotype, combo_m)
summary(imravlt_lm_m)
```

```{r odor-rec, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Recognized,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Odor percent correctly recognized linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Odor percent correctly recognized") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, Recognized, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Odor percent correctly recognized") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

odor2_lm2 <- lm(Recognized ~ age*Genotype*sex, geno_combined)
summary(odor2_lm2)

odor2_lm_f <- lm(Recognized ~ age*Genotype, combo_f)
summary(odor2_lm_f)

odor2_lm_m <- lm(Recognized ~ age*Genotype, combo_m)
summary(odor2_lm_m)
```

```{r odor-precent, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = PrecentCorrectRecall,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Odor recognition percent correct recall linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Odor recognition percent correct recall") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, PrecentCorrectRecall, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Odor recognition percent correct recall ") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

odor1_lm2 <- lm(PrecentCorrectRecall ~ age*Genotype*sex, geno_combined)
summary(odor1_lm2)

odor1_lm_f <- lm(PrecentCorrectRecall ~ age*Genotype, combo_f)
summary(odor1_lm_f)

odor1_lm_m <- lm(PrecentCorrectRecall ~ age*Genotype, combo_m)
summary(odor1_lm_m)

```

```{r delay-benson, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Delay_BensonTotal,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Total delayed Benson scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Total delayed Benson  score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, Delay_BensonTotal, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Total delayed Benson score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

dbenson_lm2 <- lm(Delay_BensonTotal ~ age*Genotype*sex, geno_combined)
summary(dbenson_lm2)

dbenson_lm_f <- lm(Delay_BensonTotal ~ age*Genotype, combo_f)
summary(dbenson_lm_f)

dbenson_lm_m <- lm(Delay_BensonTotal ~ age*Genotype, combo_m)
summary(dbenson_lm_m)
```

```{r imm-benson, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Im_BensonTotal,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Total immediate Benson scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Total immediate Benson  score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, Im_BensonTotal, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Total immediate Benson score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

imbenson_lm2 <- lm(Im_BensonTotal ~ age*Genotype*sex, geno_combined)
summary(imbenson_lm2)

imbenson_lm_f <- lm(Im_BensonTotal ~ age*Genotype, combo_f)
summary(imbenson_lm_f)

imbenson_lm_m <- lm(Im_BensonTotal ~ age*Genotype, combo_m)
summary(imbenson_lm_m)
```

```{r story-delay, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Delayed_verbatim,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Story delayed verbatim scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Story delayed verbatim score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, Delayed_verbatim, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story delayed verbatim score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

dstory_lm2 <- lm(Delayed_verbatim ~ age*Genotype*sex, geno_combined)
summary(dstory_lm2)

dstory_lm_f <- lm(Delayed_verbatim ~ age*Genotype, combo_f)
summary(dstory_lm_f)

dstory_lm_m <- lm(Delayed_verbatim ~ age*Genotype, combo_m)
summary(dstory_lm_m)
```

```{r story-imm, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Immediate_verbatim,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "Story immediate verbatim scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Story immediate verbatim score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, Immediate_verbatim, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story immediate verbatim score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

istory_lm2 <- lm(Immediate_verbatim ~ age*Genotype*sex, geno_combined)
summary(istory_lm2)

istory_lm_f <- lm(Immediate_verbatim ~ age*Genotype, combo_f)
summary(istory_lm_f)

istory_lm_m <- lm(Immediate_verbatim ~ age*Genotype, combo_m)
summary(istory_lm_m)
```

```{r moca-attn, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Attention_Digits,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "MOCA attention digits scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA attention digits score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, MOCA_Attention_Digits, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA attention digits score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

amoca_lm2 <- lm(MOCA_Attention_Digits ~ age*Genotype*sex, geno_combined)
summary(amoca_lm2)

amoca_lm_f <- lm(MOCA_Attention_Digits ~ age*Genotype, combo_f)
summary(amoca_lm_f)

amoca_lm_m <- lm(MOCA_Attention_Digits ~ age*Genotype, combo_m)
summary(amoca_lm_m)
```

```{r moca-mem, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Memory,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "MOCA memory scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA memory Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, MOCA_Memory, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA memory Score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

mmoca_lm2 <- lm(MOCA_Memory ~ age*Genotype*sex, geno_combined)
summary(mmoca_lm2)

mmoca_lm_f <- lm(MOCA_Memory ~ age*Genotype, combo_f)
summary(mmoca_lm_f)

mmoca_lm_m <- lm(MOCA_Memory ~ age*Genotype, combo_m)
summary(mmoca_lm_m)
```

```{r moca-name, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Naming,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "MOCA naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA naming Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, MOCA_Naming, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA naming Score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

nmoca_lm2 <- lm(MOCA_Naming ~ age*Genotype*sex, geno_combined)
summary(nmoca_lm2)

nmoca_lm_f <- lm(MOCA_Naming ~ age*Genotype, combo_f)
summary(nmoca_lm_f)

nmoca_lm_m <- lm(MOCA_Naming ~ age*Genotype, combo_m)
summary(nmoca_lm_m)

```

```{r moca-vis, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Visuospatial,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "MOCA visuospatial scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA visuospatial Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, MOCA_Visuospatial, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Visuospatial Score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

vmoca_lm2 <- lm(MOCA_Visuospatial ~ age*Genotype*sex, geno_combined)
summary(vmoca_lm2)

vmoca_lm_f <- lm(MOCA_Visuospatial ~ age*Genotype, combo_f)
summary(vmoca_lm_f)

vmoca_lm_m <- lm(MOCA_Visuospatial ~ age*Genotype, combo_m)
summary(vmoca_lm_m)
```

```{r moca-total, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_TOTAL,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  labs(title = "MOCA scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Total MOCA Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")

plot4 <- ggplot(geno_combined, aes(age, MOCA_TOTAL, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Total MOCA Score") +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

moca_lm2 <- lm(MOCA_TOTAL ~ age*Genotype*sex, geno_combined)
summary(moca_lm2)

moca_lm_f <- lm(MOCA_TOTAL ~ age*Genotype, combo_f)
summary(moca_lm_f)

moca_lm_m <- lm(MOCA_TOTAL ~ age*Genotype, combo_m)
summary(moca_lm_m)
```


