---
title: "Physiological Visualizatiions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, echo = FALSE)
library(tidyverse)
library(cowplot)
library(scales)
data <- read.csv("AD_DECODE_data.csv")

ad <- data %>% 
  filter(! is.na(Weight)) %>% 
  mutate(sex = case_when(
    sex == "F" ~ "Female",
    sex == "M" ~ "Male"
  )) %>% 
  filter(risk_for_ad != 3)

# data by genotypes
e23 <- ad %>% 
  filter(genotype == "APOE23") 
e33 <- ad %>% 
  filter(genotype == "APOE33")
e34 <- ad %>% 
  filter(genotype == "APOE34")

# combining genotypes 
geno_combined <- ad %>% 
  mutate(Genotype = case_when(
    genotype == "APOE23" | genotype == "APOE33" ~ "APOE3",
    genotype == "APOE34" | genotype == "APOE44" ~ "APOE4"
  )) 

# separating by sex
combo_f <- geno_combined %>% 
  filter(sex == "Female")

combo_m <- geno_combined %>% 
  filter(sex == "Male")

```

``` {r bmi}
plot1 <- ggplot(geno_combined, aes(x = age, y = BMI,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  theme_bw() 

plot4 <- ggplot(geno_combined, aes(age, BMI, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw() +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(BMI ~ age*Genotype*sex, geno_combined)
summary(lm)
lm_f <- lm(BMI ~ age*Genotype, combo_f)
summary(lm_f)
lm_m <- lm(BMI ~ age*Genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)

```

```{r bp}
plot <- ggplot(geno_combined, aes(Systolic, Diastolic,
                          color = Genotype, fill = Genotype)) +
  geom_point(aes(size = age)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  theme_bw()

plot2 <- ggplot(geno_combined, aes(Systolic, Diastolic, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(size = age)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw() +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1 <- ggplot(geno_combined, aes(x = age, y = Systolic,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  theme_bw() 

plot4 <- ggplot(geno_combined, aes(age, Systolic, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw() +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(Systolic ~ age*Genotype*sex, geno_combined)
summary(lm)
lm_f <- lm(Systolic ~ age*Genotype, combo_f)
summary(lm_f)
lm_m <- lm(Systolic ~ age*Genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)

plot1 <- ggplot(geno_combined, aes(x = age, y = Diastolic,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  theme_bw() 

plot4 <- ggplot(geno_combined, aes(age, Diastolic, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw() +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5) 

lm <- lm(Diastolic ~ age*Genotype*sex, geno_combined)
summary(lm)
lm_f <- lm(Diastolic ~ age*Genotype, combo_f)
summary(lm_f)
lm_m <- lm(Diastolic ~ age*Genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

``` {r pulse}

plot1 <- ggplot(geno_combined, aes(x = age, y = Pulse,
                          color = Genotype,  fill = Genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm") +
  theme_bw() 

plot4 <- ggplot(geno_combined, aes(age, Pulse, 
                                   color = Genotype, fill = Genotype)) + 
  geom_point(aes(shape = Risk)) + 
  facet_grid(. ~ sex) + 
  stat_smooth(method = "lm") +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw() +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot4, 0, 0, 1, .5)

lm <- lm(Pulse ~ age*Genotype*sex, geno_combined)
summary(lm)
lm_f <- lm(Pulse ~ age*Genotype, combo_f)
summary(lm_f)
lm_m <- lm(Pulse ~ age*Genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)

```

```{r phys}
ggplot(data = ad, aes(x = age, fill = genotype)) +
  geom_histogram(bins = 10) +
  #scale_y_continuous(breaks=seq(20,80,10)) +
  labs(x = "Age",
   	y = "Number of participants",
   	title = "Cohort physiological distribution",
   	subtitle = "Age by genotype")

ggplot(data = ad, aes(x = age, fill = sex)) +
  geom_histogram(bins = 10) +
  labs(x = "Age",
   	y = "Number of participants",
   	title = "Cohort physiological distribution",
   	subtitle = "Age by sex")

ggplot(ad, aes(x = age, fill = genotype)) +
  geom_density(alpha = 1/3) +
    labs(x = "Age",
   	y = "Density",
   	title = "Cohort physiological densities",
   	subtitle = "Age by genotype")

ggplot(geno_combined, aes(x = age, fill = Genotype)) +
  geom_density(alpha = 1/3) +
    labs(x = "Age",
   	y = "Density",
   	title = "Cohort physiological densities",
   	subtitle = "Age by genotype")

ggplot(ad, aes(x = age, fill = sex)) +
  geom_density(alpha = 1/3) +
    labs(x = "Age",
   	y = "Density",
   	title = "Cohort physiological densities",
   	subtitle = "Age by sex")

data <- data %>% 
  filter(Risk != "")
ggplot(data, aes(x = Risk)) +
  geom_bar() +
  labs(title = "Risk for AD in cohort")


```